Asus Aura Implementation 02
antonpup/Aurora pull request #1916
Opened 2020-02-22 00:32 UTC by Fluto

**This pull request proposes the following changes:**
- Removes old Asus implementation as it does not quite work
- Introduce AuraSDK2 support, using Asus's guidelines on how to implement it
- Asus ROG Strix Flare Support (this time with extra LEDs and a new layout)

**Known issues/To do:**
- AuraSDK2 Is known to be buggy, so this needs a lot of testing before it is merged in
- 
-

2020-02-23 04:00 UTC, Fluto commented
https://cdn.discordapp.com/attachments/542047451201404943/680956713905553453/2020-02-23_12-58-18.mp4

An example of how to set up custom keys for peripherals

2020-03-12 22:01 UTC, xQwexx requested changes

2020-03-12 22:07 UTC, Fluto commented on Project-Aurora/Project-Aurora/Devices/Asus/AsusHandler.cs
> +                AuraSdk.ReleaseControl(0);
good pickup

2020-04-07 23:27 UTC, xQwexx commented
Could you add support for asus scope(sdk name: Charm), the sdk keycodes are not working for some the ctrl and windows key, and the asus sdk not supporting the uk layout just the us one,
I already done it in this pr: [https://github.com/diogotr7/Aurora/pull/4](https://github.com/diogotr7/Aurora/pull/4)

2020-04-08 22:52 UTC, Fluto commented
I'll look into it, I have Strix Flare. The internal name for it is also charm :/
Perhaps you have a different LED count to differentiate them? What's yours? I believe if you check the log when running my build should tell you

2020-04-09 11:51 UTC, xQwexx commented
Then it is look like there is no difference for the 2 keyboard from the sdk perspective. :( Than I think the only way to differentiate them is to put multiple layout in aurora and check which one is selected.
I sending the my device information:
![image](https://user-images.githubusercontent.com/17799600/78892161-26d6fd80-7a69-11ea-8069-3c3cd6c7c43f.png)

2020-04-17 00:07 UTC, jdcmarques commented
Hi, can't seem to get my Claymore to work using the build generated by AppVeyor...
Is there anyway I can help?

2020-04-26 04:48 UTC, Fluto commented
@xQwexx I added the RIGHT_WINDOWS key (on my keyboard it's FN), but the ctrl codes seem to match so im now sure what's going on there

2020-04-26 04:49 UTC, Fluto commented
@jdcmarques That might be because of your version of Aura that is installed. There is a guide to get that correctly setup on the Discord channel #asus-aura on the Aurora Discord Server.

2020-04-26 19:13 UTC, xQwexx commented
So there is two thing first sdk hashcodes not support the uk layout so DeviceKeys.HASHTAG and DeviceKeys.BACKSLASH_UK not working so you need to set them manually, like this.
```
            //UK keyboard Layout
            if (keyCode == 0x56)
            {//Hashtag Key
                light = keyboard.Lights[(int)(3 * keyboard.Width + 13)];
            }
            else if (keyCode == 0x59)
            {//BackSlash Key
                light = keyboard.Lights[(int)(4 * keyboard.Width + 1)];
            }
            else
            {
                light = keyboard.Key[keyCode];
            }
```
Secondly asus strix scope support, because of the bigger left shift the left window and alt are not in the right place, which are not corrected by the sdk.
```
            // Asus Strix Scope
            if (keyboard.Name == "Charm")
            {
                if (keyCode == 0XDB)
                {//left window
                    light = keyboard.Lights[(int)(5 * keyboard.Width + 2)];
                }
                else if (keyCode == 0x38)
                {//left alt
                    light = keyboard.Lights[(int)(5 * keyboard.Width + 3)];
                }
            }
```

2020-04-29 12:46 UTC, Fluto commented
Added a way to test lights for custom peripheral devices. To make life easier
![test lights](https://user-images.githubusercontent.com/7686594/80597451-31ceed80-8a6b-11ea-89a1-23f5afae50f0.gif)

2020-05-18 15:04 UTC, diogotr7 approved these changes

2020-05-18 15:05 UTC, merged

2020-08-19 18:30 UTC, NicTanghe commented
i just get cant find aura sdk and i have to idea zhere to get it i can only find aura creator on my pc